apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemisSecurity
metadata:
  name: ex-keycloak
spec:
  loginModules:
    propertiesLoginModules:
    - name: internal
      users:
      - name: superman
        password: ihavepower
        roles:
        - root
    keycloakLoginModules:
    - name: 'keycloak-broker'
      moduleType: 'directAccess'
      configuration:
        realm: 'artemis-keycloak-demo'
        resource: 'artemis-broker'
        # the url has to point to keycloak service in k8s
        authServerUrl: 'http://10.109.131.209:8080/auth'
        useResourceRoleMappings: true
        principalAttribute: 'preferred_username'
        sslRequired: 'external'
        credentials:
        - key: 'secret'
          value: '9699685c-8a30-45cf-bf19-0d38bbac5fdc'
    - name: 'keycloak-console'
      moduleType: 'bearerToken'
      configuration:
        realm: 'artemis-keycloak-demo'
        resource: 'artemis-console'
        # the url has to point to keycload service in k8s or Ingress
        # this url is used by hawtio and frontend js
        # in case frontend js is outside k8s, ingress must be used
        authServerUrl: 'http://keycloak.3387.com/auth'
        principalAttribute: 'preferred_username'
        useResourceRoleMappings: true
        sslRequired: 'external'
        confidentialPort: 0
  securityDomains:
    brokerDomain:
      name: 'activemq'
      loginModules:
      - name: 'internal'
        flag: 'sufficient'
      - name: 'keycloak-broker'
        flag: 'required'
        debug: true
        reload: true
    consoleDomain:
      name: 'console'
      loginModules:
      - name: 'keycloak-console'
        flag: required
  securitySettings:
    broker:
      - match: 'Info'
        # only amq role can consume, guest role can send
        permissions:
        - operationType: 'createDurableQueue'
          roles:
          - 'amq'
        - operationType: 'deleteDurableQueue'
          roles:
          - 'amq'
        - operationType: 'createNonDurableQueue'
          roles:
          - 'amq'
        - operationType: 'deleteNonDurableQueue'
          roles:
          - 'amq'
        - operationType: 'send'
          roles:
          - 'guest'
        - operationType: 'consume'
          roles:
          - 'amq'
      - match: '#'
        permissions:
        - operationType: 'createDurableQueue'
          roles:
          - 'root'
        - operationType: 'deleteDurableQueue'
          roles:
          - 'root'
        - operationType: 'createNonDurableQueue'
          roles:
          - 'root'
        - operationType: 'deleteNonDurableQueue'
          roles:
          - 'root'
        - operationType: 'createTempQueue'
          roles:
          - 'root'
        - operationType: 'deleteTempQueue'
          roles:
          - 'root'
        - operationType: 'send'
          roles:
          - 'root'
        - operationType: 'consume'
          roles:
          - 'root'
        - operationType: 'manage'
          roles:
          - 'root'
        - operationType: 'browse'
          roles:
          - 'root'
        - operationType: 'createAddress'
          roles:
          - 'root'
        - operationType: 'deleteAddress'
          roles:
          - 'root'
    management:
      hawtioRoles:
      - 'guest'
      authorisation:
        roleAccess:
        - domain: 'org.apache.activemq.artemis'
          accessList:
          - method: 'list*'
            roles:
            - amq
            - guest
            - root
          - method: 'get*'
            roles:
            - amq
            - guest
            - root
          - method: 'is*'
            roles:
            - amq
            - guest
            - root
          - method: 'set*'
            roles:
            - amq
            - guest
            - root
          - method: 'browse*'
            roles:
            - amq
            - guest
            - root
          - method: 'count*'
            roles:
            - amq
            - guest
            - root
          - method: '*'
            roles:
            - amq
            - guest
            - root
