apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: quay.io/hgao/amq-openshift-image:v3387.9
    initImage: quay.io/hgao/init-container:v3387.56
    managementRBACEnabled: true
