apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.5
    initImage: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.5
    requireLogin: true
  console:
    expose: true
  adminUser: admin
  adminPassword: admin
