FROM registry.access.redhat.com/ubi8:8.4-211 as base_keycloak

RUN yum install -y \
       java-1.8.0-openjdk \
       java-1.8.0-openjdk-devel

ADD keycloak-12.0.3 /keycloak/12.0.3

FROM base_keycloak

ADD cfg /keycloak-cfg

RUN chmod -R g+rwx /keycloak/12.0.3


